### PR TITLE
Port Kubernetes Network Policy from online to connected

### PR DESCRIPTION
**Pull request by heoelri**
This PR ports the existing Network Policy implementation from Azure Mission-Critical-Online to Azure Mission-Critical-Connected.

See https://github.com/Azure/Mission-Critical-Online/pull/46 for more.

### CODE REVIEW

**Comment by sebader** [comment]
do you want to give this an e2e run?

**Comment by sebader** [comment]
do you want to give this an e2e run?

**Comment by heoelri** [comment]
> do you want to give this an e2e run?

Yes! Here we go: https://dev.azure.com/mission-critical/Connected/_build/results?buildId=1042&view=results

**Comment by heoelri** [comment]
Successfully tested here: https://dev.azure.com/mission-critical/Connected/_build/results?buildId=1139&view=logs&s=f7e86c70-3a53-5d7e-c6ab-6506182419e7

**Review by sebader — APPROVED** [review]

**Pull request merged**
