### PR TITLE
Bump Terraform's azurerm provider to 3.0.2

### PR DESCRIPTION
**Pull request by heoelri**
In alignment with https://github.com/Azure/Mission-Critical-Online/pull/250

### CODE REVIEW

**Comment by sebader** [comment]
Please run e2e

**Comment by heoelri** [comment]
> Please run e2e

In progress: https://dev.azure.com/mission-critical/Connected/_build/results?buildId=822&view=results

**Comment by sebader** [comment]
> > Please run e2e
> 
> 
> 
> In progress: https://dev.azure.com/mission-critical/Connected/_build/results?buildId=822&view=results

Ah, GitHub mobile doesn't show this under checks 🙃

**Comment by heoelri** [comment]
Deployment (only) verified in E2E: https://dev.azure.com/mission-critical/Connected/_build/results?buildId=823&view=results

image

Interestingly enough has the destroy part failed in the first place but was re-tried (automatically; as expected) and succeeded in its second run.

**Comment by heoelri** [comment]
Testing it in another complete e2e run again: https://dev.azure.com/mission-critical/Connected/_build/results?buildId=823&view=results

**Comment by heoelri** [comment]
The first destroy run always fails. @sebader I wonder if this is expected in connected. 

```console
│ Error: purging of Secret "StorageAccount-Healthservice-ContainerName" (Key Vault "[https://ace2ebf70-westeurop-kv.vault.azure.net/"](https://ace2ebf70-westeurop-kv.vault.azure.net/%22)) : keyvault.BaseClient#PurgeDeletedSecret: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: Service returned an error. Status=403 Code="Forbidden" Message="Operation \"purge\" is not allowed because purge protection is enabled for this vault. Key Vault service will automatically purge it after the retention period has passed.\r\nVault: ace2ebf70-westeurop-kv;location=westeurope"

│ Error: purging of Secret "Frontend-SenderEventHubConnectionString" (Key Vault "[https://ace2ebf70-westeurop-kv.vault.azure.net/"](https://ace2ebf70-westeurop-kv.vault.azure.net/%22)) : keyvault.BaseClient#PurgeDeletedSecret: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: Service returned an error. Status=403 Code="Forbidden" Message="Operation \"purge\" is not allowed because purge protection is enabled for this vault. Key Vault service will automatically purge it after the retention period has passed.\r\nVault: ace2ebf70-westeurop-kv;location=westeurope"

│ Error: purging of Secret "APPINSIGHTS-INSTRUMENTATIONKEY" (Key Vault "[https://ace2ebf70-westeurop-kv.vault.azure.net/"](https://ace2ebf70-westeurop-kv.vault.azure.net/%22)) : keyvault.BaseClient#PurgeDeletedSecret: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: Service returned an error. Status=403 Code="Forbidden" Message="Operation \"purge\" is not allowed because purge protection is enabled for this vault. Key Vault service will automatically purge it after the retention period has passed.\r\nVault: ace2ebf70-westeurop-kv;location=westeurope"

│ Error: purging of Secret "CosmosDb-Endpoint" (Key Vault "[https://ace2ebf70-westeurop-kv.vault.azure.net/"](https://ace2ebf70-westeurop-kv.vault.azure.net/%22)) : keyvault.BaseClient#PurgeDeletedSecret: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: Service returned an error. Status=403 Code="Forbidden" Message="Operation \"purge\" is not allowed because purge protection is enabled for this vault. Key Vault service will automatically purge it after the retention period has passed.\r\nVault: ace2ebf70-westeurop-kv;location=westeurope"
```

**Comment by sebader** [comment]
Interesting. I'll see if that is already the case with 2.x

**Comment by heoelri** [comment]
> Interesting. I'll see if that is already the case with 2.x

I noticed one difference in connected:

```hcl
provider "azurerm" {
  features {
    key_vault {
      purge_soft_delete_on_destroy = false
    }
```

Why's that only configured in connected?

**Comment by sebader** [comment]
on 2.x e2e it seemed fine, or where did you see the retry? https://dev.azure.com/Mission-Critical/Connected/_build/results?buildId=765&view=logs&j=ebbdc2b5-c867-5b15-f4ca-489b91c137dc&t=0507d09c-dfcd-57f4-31c1-d2e75e0ea42f

**Comment by heoelri** [comment]
Works - https://dev.azure.com/mission-critical/Connected/_build/results?buildId=833&view=results

**Review by sebader — APPROVED** [review]

**Pull request merged**
